- generic [active] [ref=e1]:
  - banner [ref=e2]:
    - generic [ref=e4]:
      - generic [ref=e5]:
        - link "Alphascope" [ref=e6] [cursor=pointer]:
          - /url: /
          - img "Alphascope" [ref=e7]
        - navigation [ref=e8]:
          - link "Forecast" [ref=e9] [cursor=pointer]:
            - /url: /forecast
          - link "Predictions" [ref=e10] [cursor=pointer]:
            - /url: /predictions
          - link "Odds" [ref=e11] [cursor=pointer]:
            - /url: /odds
          - link "News" [ref=e12] [cursor=pointer]:
            - /url: /news
          - link "Blog" [ref=e13] [cursor=pointer]:
            - /url: /blog
      - link "Get Started Free" [ref=e15] [cursor=pointer]:
        - /url: /onboarding
        - generic [ref=e16]:
          - generic [ref=e17]: Get Started Free
          - img [ref=e18]
  - generic [ref=e20]:
    - generic [ref=e21]:
      - generic [ref=e23]:
        - generic [ref=e27]: Trusted by 10,000+ traders
        - heading "Predict Markets Before They Move" [level=1] [ref=e28]
        - paragraph [ref=e29]: AI-driven intelligence for prediction markets. Analyze events, uncover signals, and stay ahead across Polymarket, Kalshi, and more.
        - generic [ref=e30]:
          - button "Get Started Free" [ref=e31] [cursor=pointer]:
            - generic [ref=e32]:
              - img [ref=e33]
              - generic [ref=e36]: Get Started Free
          - button "View Markets" [ref=e37] [cursor=pointer]:
            - text: View Markets
            - img [ref=e38]
        - generic [ref=e40]:
          - generic [ref=e41]: Works with
          - generic [ref=e42]:
            - img "Polymarket" [ref=e45]
            - generic [ref=e46]: Polymarket
          - generic [ref=e47]:
            - img "Kalshi" [ref=e50]
            - generic [ref=e51]: Kalshi
          - generic [ref=e52]:
            - img "Manifold" [ref=e55]
            - generic [ref=e56]: Manifold
          - generic [ref=e57]:
            - img "Opinion" [ref=e60]
            - generic [ref=e61]: Opinion
      - generic [ref=e63]:
        - generic [ref=e64]:
          - generic [ref=e65]: 0k+
          - generic [ref=e66]: Markets Tracked
        - generic [ref=e67]:
          - generic [ref=e68]: "0"
          - generic [ref=e69]: Platforms
        - generic [ref=e70]:
          - generic [ref=e71]: 24/7
          - generic [ref=e72]: Real-time Data
        - generic [ref=e73]:
          - generic [ref=e74]: Free
          - generic [ref=e75]: To Get Started
      - generic [ref=e76]:
        - generic [ref=e77]:
          - text: How It Works
          - heading "How Alphascope Works" [level=2] [ref=e78]
          - paragraph [ref=e79]: Comprehensive tooling built for prediction market traders who want an edge.
        - generic [ref=e80]:
          - generic [ref=e81]:
            - generic [ref=e84]:
              - generic [ref=e85]:
                - generic [ref=e86]:
                  - generic [ref=e87]: Will Bitcoin hit $150k?
                  - generic [ref=e88]: ACTIVE
                - generic [ref=e90]:
                  - generic [ref=e91]:
                    - generic [ref=e92]: Market Price
                    - generic [ref=e93]: 62%
                  - generic [ref=e94]:
                    - generic [ref=e95]: AI Prediction
                    - generic [ref=e96]: 78%
                  - generic [ref=e97]:
                    - img [ref=e98]
                    - generic [ref=e101]: +16%
              - generic [ref=e103]:
                - generic [ref=e104]: Confidence
                - generic [ref=e105]: High
            - generic [ref=e108]:
              - heading "AI-Powered Predictions" [level=3] [ref=e109]
              - paragraph [ref=e110]: Our models analyze market data, news, and patterns to predict probabilities before the market catches up.
          - generic [ref=e111]:
            - generic [ref=e114]:
              - generic [ref=e115]:
                - generic [ref=e116]:
                  - generic [ref=e117]: 🇺🇸
                  - generic [ref=e118]: Fed Rate Decision
                - generic [ref=e119]: High
              - generic [ref=e120]:
                - generic [ref=e121]:
                  - generic [ref=e122]: 📰
                  - generic [ref=e123]: Trump Tariff Annou...
                - generic [ref=e124]: Medium
              - generic [ref=e125]:
                - generic [ref=e126]:
                  - generic [ref=e127]: 🌍
                  - generic [ref=e128]: EU Regulation Vote
                - generic [ref=e129]: Low
              - generic [ref=e130]:
                - generic [ref=e131]:
                  - generic [ref=e132]: AI Impact
                  - generic [ref=e133]: 9/10
                - generic [ref=e135]: 3 Markets
            - generic [ref=e136]:
              - heading "News Impact Analysis" [level=3] [ref=e137]
              - paragraph [ref=e138]: AI ranks breaking news by market impact, so you know exactly which events move prices.
          - generic [ref=e139]:
            - generic [ref=e142]:
              - generic [ref=e143]:
                - generic [ref=e144]:
                  - generic [ref=e147]: Polymarket
                  - generic [ref=e148]: LIVE
                - generic [ref=e149]:
                  - generic [ref=e150]:
                    - generic [ref=e151]: Probability
                    - generic [ref=e152]: 67%
                  - generic [ref=e153]:
                    - generic [ref=e154]: Volume
                    - generic [ref=e155]: $1.2M
              - generic [ref=e164]:
                - generic [ref=e165]:
                  - generic [ref=e168]: Kalshi
                  - generic [ref=e169]: LIVE
                - generic [ref=e170]:
                  - generic [ref=e171]:
                    - generic [ref=e172]: Probability
                    - generic [ref=e173]: 64%
                  - generic [ref=e174]:
                    - generic [ref=e175]: Volume
                    - generic [ref=e176]: $890K
              - generic [ref=e185]: + Manifold, Opinion & more
            - generic [ref=e186]:
              - heading "Multi-Platform Tracking" [level=3] [ref=e187]
              - paragraph [ref=e188]: Track the same events across Polymarket, Kalshi, Manifold, and more from one dashboard.
        - generic [ref=e189]:
          - generic [ref=e191]:
            - generic [ref=e192]:
              - heading "Real-time Probability Charts" [level=3] [ref=e193]
              - paragraph [ref=e194]: Watch probabilities shift in real time with interactive charts, news markers, and trend analysis.
            - img [ref=e197]:
              - generic [ref=e198]: 100%
              - generic [ref=e199]: 75%
              - generic [ref=e200]: 50%
              - generic [ref=e201]: 25%
              - generic [ref=e208]: 78.2%
              - generic [ref=e212]: News catalyst
          - generic [ref=e214]:
            - generic [ref=e215]:
              - heading "Spot Arbitrage Across Platforms" [level=3] [ref=e216]
              - paragraph [ref=e217]: Detect pricing discrepancies between platforms and find risk-free opportunities instantly.
            - generic [ref=e220]:
              - generic [ref=e221]:
                - generic [ref=e222]: Same event, different prices
                - generic [ref=e223]: "\"Will AI regulation pass in 2026?\""
                - generic [ref=e224]:
                  - generic [ref=e225]:
                    - generic [ref=e226]: Polymarket
                    - generic [ref=e227]: 72%
                  - generic [ref=e228]:
                    - generic [ref=e229]: 8%
                    - img [ref=e230]
                    - generic [ref=e233]: spread
                  - generic [ref=e234]:
                    - generic [ref=e235]: Kalshi
                    - generic [ref=e236]: 64%
              - generic [ref=e238]:
                - img [ref=e239]
                - generic [ref=e241]: Arbitrage Opportunity
      - generic [ref=e243]:
        - generic [ref=e244]:
          - text: Features
          - heading "Powerful Market Insights" [level=2] [ref=e245]
          - paragraph [ref=e246]: Alphascope gives you data-driven intelligence for prediction markets, enabling smarter decisions that lead to better outcomes.
        - generic [ref=e247]:
          - generic [ref=e248]:
            - generic [ref=e251]:
              - generic [ref=e253]:
                - img [ref=e254]
                - generic [ref=e266]: AI Market Impact
              - generic [ref=e268]:
                - generic [ref=e270]: 8/10
                - paragraph [ref=e271]: The new tariff announcement significantly impacts trade-related prediction markets, with AI models detecting a 23% probability shift across 5 active markets.
              - generic [ref=e272]:
                - generic [ref=e273]: Politics
                - generic [ref=e274]: Trade
                - generic [ref=e275]: 5 Markets
            - generic [ref=e276]:
              - heading "AI Probability Score" [level=3] [ref=e277]
              - paragraph [ref=e278]: Alphascope rates market outcomes with an AI confidence score, so you know exactly how likely each event is.
          - generic [ref=e279]:
            - generic [ref=e282]:
              - generic [ref=e283]:
                - img [ref=e284]
                - generic [ref=e289]: Impacted Markets
              - generic [ref=e290]:
                - generic [ref=e291]:
                  - generic [ref=e292]:
                    - generic [ref=e293]: Will tariffs pass?
                    - generic [ref=e294]: Bullish
                  - generic [ref=e295]:
                    - generic [ref=e296]: Polymarket
                    - generic [ref=e297]: +12%
                  - paragraph [ref=e298]: New tariff policy increases likelihood, driving market probability upward.
                - generic [ref=e300]:
                  - generic [ref=e301]:
                    - generic [ref=e302]: EU trade deal by 2026?
                    - generic [ref=e303]: Bearish
                  - generic [ref=e304]:
                    - generic [ref=e305]: Kalshi
                    - generic [ref=e306]: "-8%"
                  - paragraph [ref=e307]: Trade tensions reduce deal probability, shifting sentiment bearish.
            - generic [ref=e308]:
              - heading "Impacted Markets" [level=3] [ref=e309]
              - paragraph [ref=e310]: See which prediction markets are affected by breaking news and how probabilities shift in response.
        - generic [ref=e311]:
          - generic [ref=e312]:
            - img [ref=e315]:
              - generic [ref=e316]: 100%
              - generic [ref=e317]: 75%
              - generic [ref=e318]: 50%
              - generic [ref=e319]: 25%
              - generic [ref=e320]: Jan
              - generic [ref=e321]: Feb
              - generic [ref=e322]: Mar
              - generic [ref=e323]: Apr
              - generic [ref=e327]: AI Forecast
              - generic [ref=e328]: Actual
            - generic [ref=e331]:
              - heading "Forecast vs Actual Charts" [level=3] [ref=e332]
              - paragraph [ref=e333]: Compare AI forecasts against real outcomes with interactive probability charts over time.
          - generic [ref=e334]:
            - generic [ref=e336]:
              - generic [ref=e337]:
                - generic [ref=e338]:
                  - generic [ref=e339]: 2 min ago
                  - generic [ref=e340]: High
                - generic [ref=e341]: Probability spike detected
                - generic [ref=e342]: Will AI bill pass?
              - generic [ref=e343]:
                - generic [ref=e344]:
                  - generic [ref=e345]: 15 min ago
                  - generic [ref=e346]: Medium
                - generic [ref=e347]: Unusual volume surge
                - generic [ref=e348]: Fed rate cut by June
              - generic [ref=e349]:
                - generic [ref=e350]:
                  - generic [ref=e351]: 1 hr ago
                  - generic [ref=e352]: High
                - generic [ref=e353]: News catalyst found
                - generic [ref=e354]: Trump wins nomination
            - generic [ref=e355]:
              - heading "Smart Market Alerts" [level=3] [ref=e356]
              - paragraph [ref=e357]: Get notified when AI detects mispriced markets, unusual volume, or news-driven probability shifts.
        - generic [ref=e358]:
          - generic [ref=e359]:
            - generic [ref=e362]:
              - generic [ref=e363]:
                - generic [ref=e364]: Platform
                - generic [ref=e365]:
                  - generic [ref=e366]: All
                  - generic [ref=e367]: Polymarket
                  - generic [ref=e368]: Kalshi
              - generic [ref=e369]:
                - generic [ref=e370]: Category
                - generic [ref=e371]:
                  - generic [ref=e372]: Politics
                  - generic [ref=e373]: Crypto
                  - generic [ref=e374]: Sports
                  - generic [ref=e375]: Tech
              - generic [ref=e376]:
                - generic [ref=e377]: Probability Range
                - generic [ref=e381]: 20% – 70%
              - generic [ref=e382]:
                - generic [ref=e383]: Min Volume
                - generic [ref=e387]: $50K+
            - generic [ref=e388]:
              - heading "Custom Market Filters" [level=3] [ref=e389]
              - paragraph [ref=e390]: Filter markets by platform, category, probability range, and volume to find the best opportunities.
          - generic [ref=e391]:
            - generic [ref=e396]:
              - generic [ref=e397]:
                - img [ref=e399]
                - img [ref=e402]
                - img [ref=e415]
              - text: Stay Updated!
              - generic [ref=e418]:
                - generic [ref=e419]: Portfolio Tracking
                - generic [ref=e420]: Auto Strategies
                - generic [ref=e421]: AI Reports
            - generic [ref=e422]:
              - heading "Coming Soon" [level=3] [ref=e423]
              - paragraph [ref=e424]: Portfolio tracking, automated strategies, and AI-generated market reports are on the way.
      - generic [ref=e425]:
        - generic [ref=e426]:
          - text: Live Markets
          - heading "Trending Prediction Markets" [level=2] [ref=e427]
          - paragraph [ref=e428]: Real-time data from the top prediction market platforms
        - generic [ref=e431]:
          - generic [ref=e434] [cursor=pointer]:
            - generic [ref=e435]:
              - generic [ref=e436]: Kalshi
              - generic [ref=e437]:
                - img [ref=e438]
                - generic [ref=e441]: 64%
            - paragraph [ref=e442]: BTC price on May 31, 2026 at 7pm EDT?
            - generic [ref=e444]: $0
          - generic [ref=e447] [cursor=pointer]:
            - generic [ref=e448]:
              - generic [ref=e449]: Kalshi
              - generic [ref=e450]:
                - img [ref=e451]
                - generic [ref=e452]: 50%
            - paragraph [ref=e453]: BTC 15 min · $73,973.13 target
            - generic [ref=e455]: $0
          - generic [ref=e458] [cursor=pointer]:
            - generic [ref=e459]:
              - generic [ref=e460]: Kalshi
              - generic [ref=e461]:
                - img [ref=e462]
                - generic [ref=e463]: 50%
            - paragraph [ref=e464]: BTC 15 min · $73,906.37 target
            - generic [ref=e466]: $0
          - generic [ref=e469] [cursor=pointer]:
            - generic [ref=e470]:
              - generic [ref=e471]: Kalshi
              - generic [ref=e472]:
                - img [ref=e473]
                - generic [ref=e476]: 66%
            - paragraph [ref=e477]: Jovic vs Osaka
            - generic [ref=e479]: $0
          - generic [ref=e482] [cursor=pointer]:
            - generic [ref=e483]:
              - generic [ref=e484]: Kalshi
              - generic [ref=e485]:
                - img [ref=e486]
                - generic [ref=e489]: 64%
            - paragraph [ref=e490]: BTC price on May 31, 2026 at 7pm EDT?
            - generic [ref=e492]: $0
          - generic [ref=e495] [cursor=pointer]:
            - generic [ref=e496]:
              - generic [ref=e497]: Kalshi
              - generic [ref=e498]:
                - img [ref=e499]
                - generic [ref=e500]: 50%
            - paragraph [ref=e501]: BTC 15 min · $73,973.13 target
            - generic [ref=e503]: $0
          - generic [ref=e506] [cursor=pointer]:
            - generic [ref=e507]:
              - generic [ref=e508]: Kalshi
              - generic [ref=e509]:
                - img [ref=e510]
                - generic [ref=e511]: 50%
            - paragraph [ref=e512]: BTC 15 min · $73,906.37 target
            - generic [ref=e514]: $0
          - generic [ref=e517] [cursor=pointer]:
            - generic [ref=e518]:
              - generic [ref=e519]: Kalshi
              - generic [ref=e520]:
                - img [ref=e521]
                - generic [ref=e524]: 66%
            - paragraph [ref=e525]: Jovic vs Osaka
            - generic [ref=e527]: $0
          - generic [ref=e530] [cursor=pointer]:
            - generic [ref=e531]:
              - generic [ref=e532]: Kalshi
              - generic [ref=e533]:
                - img [ref=e534]
                - generic [ref=e537]: 64%
            - paragraph [ref=e538]: BTC price on May 31, 2026 at 7pm EDT?
            - generic [ref=e540]: $0
          - generic [ref=e543] [cursor=pointer]:
            - generic [ref=e544]:
              - generic [ref=e545]: Kalshi
              - generic [ref=e546]:
                - img [ref=e547]
                - generic [ref=e548]: 50%
            - paragraph [ref=e549]: BTC 15 min · $73,973.13 target
            - generic [ref=e551]: $0
          - generic [ref=e554] [cursor=pointer]:
            - generic [ref=e555]:
              - generic [ref=e556]: Kalshi
              - generic [ref=e557]:
                - img [ref=e558]
                - generic [ref=e559]: 50%
            - paragraph [ref=e560]: BTC 15 min · $73,906.37 target
            - generic [ref=e562]: $0
          - generic [ref=e565] [cursor=pointer]:
            - generic [ref=e566]:
              - generic [ref=e567]: Kalshi
              - generic [ref=e568]:
                - img [ref=e569]
                - generic [ref=e572]: 66%
            - paragraph [ref=e573]: Jovic vs Osaka
            - generic [ref=e575]: $0
      - generic [ref=e578]:
        - heading "Ready to Predict Smarter?" [level=2] [ref=e579]
        - paragraph [ref=e580]: Join traders using AI to get ahead on Polymarket, Kalshi, and other prediction markets. Free to start.
        - paragraph [ref=e581]: Live data from 4 platforms • No credit card required
        - button "Get Started Free" [ref=e583] [cursor=pointer]:
          - generic [ref=e584]:
            - generic [ref=e585]: Get Started Free
            - img [ref=e586]
    - article [ref=e590]:
      - generic [ref=e591]:
        - heading "What Alphascope does for prediction market traders" [level=2] [ref=e592]
        - paragraph [ref=e593]: Alphascope is a research workspace for people who follow Polymarket, Kalshi, and other prediction markets. The product brings live odds, AI forecasts, news impact analysis, and market pages into one crawlable workflow. Instead of opening several dashboards, scanning social feeds, and manually checking whether a headline matches the contract, users can start from a market, a category, or a plain-English question and move toward the evidence behind the price.
        - paragraph [ref=e594]: Prediction market prices are useful because they compress many opinions into one number, but the number alone is not enough. A Yes price can be high because the event is likely, because liquidity is thin, because traders are reacting to a headline, or because another related contract moved first. Alphascope helps separate those cases by pairing the price with context.
      - generic [ref=e595]:
        - heading "The Alphascope research workflow" [level=2] [ref=e596]
        - paragraph [ref=e597]: A typical workflow starts on the live odds board. Users scan active categories such as elections, economy, sports, and crypto, then open a specific market page. The market page shows the current implied probability, the platform, and the AI forecast context. From there, users can review market-moving news, compare related contracts, and decide whether the current price still leaves enough edge after fees, spread, and settlement risk.
        - paragraph [ref=e598]: Another workflow starts from news. If a headline appears to move a set of markets, users can open the affected contracts and compare the move with the resolution criteria. This is useful when traders are not sure whether a story is a real catalyst or only a temporary sentiment shock. The strongest setup is a story that directly affects settlement and has not yet been fully reflected in the live price.
      - generic [ref=e599]:
        - heading "Why AI forecasts need live market context" [level=2] [ref=e600]
        - paragraph [ref=e601]: A model forecast can be directionally useful and still be a poor trade if the market price is already better informed. That is why Alphascope keeps forecasts near live odds rather than presenting AI predictions as standalone picks. The value comes from the gap between the model's reasoning and the market's current consensus. When that gap is large, the next step is to understand why. When the gap is small, the market may already be efficient.
        - paragraph [ref=e602]: Live context also helps avoid false confidence. If a forecast points to a 60 percent outcome and the market is 58 percent, the difference may not justify risk. If the market is 40 percent, the gap may deserve deeper review, but only after checking liquidity and settlement. By keeping those checks together, Alphascope makes the decision more disciplined.
      - generic [ref=e603]:
        - heading "Markets and categories Alphascope covers" [level=2] [ref=e604]
        - paragraph [ref=e605]: Election markets often depend on polls, fundraising, candidate news, legal decisions, turnout signals, and party-control dynamics. Economy markets depend on data releases, Federal Reserve communication, inflation prints, jobs reports, and revisions. Sports markets depend on injuries, lineups, scheduling, weather, and in-game volatility. Crypto markets depend on spot prices, exchange news, ETF flows, regulation, and sudden liquidity changes.
        - paragraph [ref=e606]: "Each category needs a different research rhythm, but the core process is the same: read the question, check the price, inspect the catalyst, compare related markets, and size risk only if the edge survives execution costs. Alphascope is built to make that process faster without hiding the uncertainty that makes prediction markets interesting."
      - generic [ref=e607]:
        - heading "Where to go next" [level=2] [ref=e608]
        - paragraph [ref=e609]:
          - text: Start with
          - link "live prediction market odds" [ref=e610] [cursor=pointer]:
            - /url: /odds
          - text: if you want to scan the board,
          - link "AI predictions" [ref=e611] [cursor=pointer]:
            - /url: /predictions
          - text: if you want markets ranked with forecast context,
          - link "news impact" [ref=e612] [cursor=pointer]:
            - /url: /news
          - text: if a catalyst is moving prices, or
          - link "the forecast composer" [ref=e613] [cursor=pointer]:
            - /url: /forecast
          - text: if you already have a specific link or question. Each path leads back to the same research loop, so users can move from broad discovery to specific market analysis without losing context.
        - paragraph [ref=e614]: "The goal is a cleaner prediction market workflow: fewer stale prices missed, fewer headlines traded without contract context, and fewer assumptions about whether Polymarket and Kalshi are asking the exact same question. That is the practical reason for combining odds, news, AI forecasts, and internally linked market pages in one place."
      - generic [ref=e615]:
        - heading "Why crawlable market context matters" [level=2] [ref=e616]
        - paragraph [ref=e617]: Many prediction market products hide useful context inside private dashboards, client-only state, or short cards that are hard for search engines to interpret. Alphascope keeps important market context in crawlable pages so users can find the same research path from search, social links, or direct navigation. That includes the market title, category, platform, current probability, related research links, and plain-language explanation of how the odds should be read.
        - paragraph [ref=e618]: Crawlable context also helps users revisit a market later. A prediction market can change quickly, and a transient app state is easy to lose. A stable page lets users compare today's price with the next news cycle, share a contract with another researcher, and move between topic pages without starting the workflow over.
      - generic [ref=e619]:
        - heading "How traders can combine categories" [level=2] [ref=e620]
        - paragraph [ref=e621]: The strongest research often crosses categories. A political event can affect regulatory markets, crypto markets, and economy markets. A macro data release can affect Fed odds, equities, crypto, and recession contracts. A sports injury can affect game winner contracts, player props, and championship odds. Alphascope groups categories separately for scanning, but the research workflow is designed to move across categories when a catalyst has broader impact.
        - paragraph [ref=e622]: This is where related market review matters. If one market moves and a nearby market does not, the difference may be a lead-lag opportunity. If every related market moves at once, the board may already understand the catalyst. If the markets move in conflicting directions, the first task is to check whether the questions are actually equivalent. The homepage links into each of those research paths.
      - generic [ref=e623]:
        - heading "A simple checklist before acting on a market" [level=2] [ref=e624]
        - paragraph [ref=e625]: Before acting on any market, write down the live probability, your estimate, the strongest evidence for your estimate, the strongest evidence against it, the settlement source, and the maximum amount you are willing to lose. Then check the spread and liquidity. If the position only looks attractive before execution costs, the edge is probably not strong enough. If the contract language is ambiguous, reduce size or skip the trade.
        - paragraph [ref=e626]: Alphascope is designed to support that checklist without turning it into busywork. The odds board gives the price, the forecast gives structured reasoning, the news page gives catalysts, and the tool pages help with probability and payout math. The trader still makes the decision, but the information is organized so fewer important checks are missed.
      - generic [ref=e627]:
        - heading "How Alphascope differs from a static market list" [level=2] [ref=e628]
        - paragraph [ref=e629]: "A static market list tells you what is available. Alphascope is designed to show what deserves research next. The difference is the connection between pages: a live market can lead to a forecast, a forecast can lead to news, a news item can lead back to related markets, and a calculator can turn the final price into payout and risk. That creates a loop users can repeat whenever a new catalyst appears."
        - paragraph [ref=e630]: This structure also keeps the homepage useful for visitors who do not already know which market they want. They can start with the product overview, move into odds or forecasts, and learn how the pieces fit together before committing to a specific contract. That makes the page more informative than a hero section plus a few market cards.
      - generic [ref=e631]:
        - heading "Research habits Alphascope is built to reinforce" [level=2] [ref=e632]
        - paragraph [ref=e633]: The first habit is writing down a probability before looking for confirmation. The second is checking whether the market's settlement rule matches the story being discussed. The third is comparing a market with nearby contracts instead of treating it as isolated. The fourth is measuring payout and downside before increasing size. The fifth is being willing to skip a market when the edge depends on a weak source or a wide spread.
        - paragraph [ref=e634]: Alphascope cannot make those decisions for the user, and it should not try to. Its job is to organize the information so the habits are easier to follow. A trader who consistently checks price, rules, liquidity, news, related markets, and payout will avoid many of the mistakes that come from trading only the most exciting headline.
      - generic [ref=e635]:
        - heading "How to move from discovery to a decision" [level=2] [ref=e636]
        - paragraph [ref=e637]: "Discovery starts with finding markets that are active enough to deserve attention. Decision making starts only after the market has passed a stricter filter: clear settlement language, a price that differs from your estimate, enough liquidity to enter, and a catalyst that can be verified from a reliable source. Alphascope is built to separate those two phases so users do not confuse an interesting market with an actionable one."
        - paragraph [ref=e638]: "That distinction matters on every visit. Some users arrive to scan broad categories, some arrive from a news headline, and some arrive with a specific Polymarket or Kalshi link. Each path should end in the same disciplined question: does this contract still offer value at the current price after spread, fees, liquidity, correlation, and settlement risk? If the answer is unclear, the next step is more research, not a larger position."
      - generic [ref=e639]:
        - heading "Why fewer stronger signals beat a noisy feed" [level=2] [ref=e640]
        - paragraph [ref=e641]: A noisy feed can make every price move feel urgent. A stronger research system filters for the few markets where the question, catalyst, liquidity, and forecast disagreement are all worth attention. Alphascope keeps the homepage focused on the main research paths so users can choose the right starting point instead of scrolling through every available contract at once.
        - paragraph [ref=e642]: Once a user needs breadth, the dedicated odds and predictions pages provide it. The homepage should introduce the workflow, show current market context, and point to deeper pages. That balance gives users enough live information to understand the product while keeping the page readable, crawlable, and focused on the next research step.
  - contentinfo [ref=e643]:
    - generic [ref=e644]:
      - generic [ref=e645]:
        - generic [ref=e646]:
          - heading "Product" [level=3] [ref=e647]
          - list [ref=e648]:
            - listitem [ref=e649]:
              - link "Predictions" [ref=e650] [cursor=pointer]:
                - /url: /predictions
            - listitem [ref=e651]:
              - link "Odds" [ref=e652] [cursor=pointer]:
                - /url: /odds
            - listitem [ref=e653]:
              - link "News" [ref=e654] [cursor=pointer]:
                - /url: /news
            - listitem [ref=e655]:
              - link "Blog" [ref=e656] [cursor=pointer]:
                - /url: /blog
            - listitem [ref=e657]:
              - link "Site Index" [ref=e658] [cursor=pointer]:
                - /url: /site-index
            - listitem [ref=e659]:
              - link "Polymarket vs Kalshi" [ref=e660] [cursor=pointer]:
                - /url: /compare/polymarket-vs-kalshi
        - generic [ref=e661]:
          - heading "Markets" [level=3] [ref=e662]
          - list [ref=e663]:
            - listitem [ref=e664]:
              - link "Election Odds" [ref=e665] [cursor=pointer]:
                - /url: /odds/elections
            - listitem [ref=e666]:
              - link "Economy & Fed" [ref=e667] [cursor=pointer]:
                - /url: /odds/economy
            - listitem [ref=e668]:
              - link "Sports Odds" [ref=e669] [cursor=pointer]:
                - /url: /odds/sports
            - listitem [ref=e670]:
              - link "Crypto Odds" [ref=e671] [cursor=pointer]:
                - /url: /odds/crypto
        - generic [ref=e672]:
          - heading "Popular" [level=3] [ref=e673]
          - list [ref=e674]:
            - listitem [ref=e675]:
              - link "Trump Odds" [ref=e676] [cursor=pointer]:
                - /url: /odds/topic/trump
            - listitem [ref=e677]:
              - link "Bitcoin Odds" [ref=e678] [cursor=pointer]:
                - /url: /odds/topic/bitcoin
            - listitem [ref=e679]:
              - link "Fed Rate Odds" [ref=e680] [cursor=pointer]:
                - /url: /odds/topic/fed-rate
            - listitem [ref=e681]:
              - link "NFL Odds" [ref=e682] [cursor=pointer]:
                - /url: /odds/topic/nfl
            - listitem [ref=e683]:
              - link "Presidential Election" [ref=e684] [cursor=pointer]:
                - /url: /odds/topic/presidential-election
        - generic [ref=e685]:
          - heading "Tools & Guides" [level=3] [ref=e686]
          - list [ref=e687]:
            - listitem [ref=e688]:
              - link "Odds Calculator" [ref=e689] [cursor=pointer]:
                - /url: /tools/odds-calculator
            - listitem [ref=e690]:
              - link "Polymarket Wallet Tracker" [ref=e691] [cursor=pointer]:
                - /url: /tools/polymarket-wallet-tracker
            - listitem [ref=e692]:
              - link "Polymarket Best AI" [ref=e693] [cursor=pointer]:
                - /url: /tools/polymarket-best-ai
            - listitem [ref=e694]:
              - link "Kalshi Trustpilot" [ref=e695] [cursor=pointer]:
                - /url: /compare/kalshi-trustpilot
            - listitem [ref=e696]:
              - link "Profit Calculator" [ref=e697] [cursor=pointer]:
                - /url: /tools/profit-calculator
            - listitem [ref=e698]:
              - link "How to Bet on Elections" [ref=e699] [cursor=pointer]:
                - /url: /how-to/bet-on-elections
            - listitem [ref=e700]:
              - link "How to Bet on Bitcoin" [ref=e701] [cursor=pointer]:
                - /url: /how-to/bet-on-bitcoin
            - listitem [ref=e702]:
              - link "How to Bet on Sports" [ref=e703] [cursor=pointer]:
                - /url: /how-to/bet-on-sports
        - generic [ref=e704]:
          - heading "Company" [level=3] [ref=e705]
          - list [ref=e706]:
            - listitem [ref=e707]:
              - link "Terms of Service" [ref=e708] [cursor=pointer]:
                - /url: /terms
            - listitem [ref=e709]:
              - link "Privacy Policy" [ref=e710] [cursor=pointer]:
                - /url: /privacy
            - listitem [ref=e711]:
              - link "Refund Policy" [ref=e712] [cursor=pointer]:
                - /url: /refund-policy
            - listitem [ref=e713]:
              - link "X Twitter / X" [ref=e714] [cursor=pointer]:
                - /url: https://x.com/xalphascope
                - img "X" [ref=e715]
                - text: Twitter / X
            - listitem [ref=e716]:
              - link "Telegram Telegram" [ref=e717] [cursor=pointer]:
                - /url: https://t.me/alphascopee
                - img "Telegram" [ref=e718]
                - text: Telegram
      - generic [ref=e719]:
        - generic [ref=e720]:
          - img "Alphascope" [ref=e721]
          - generic [ref=e722]: © 2026 Alphascope. All rights reserved.
        - paragraph [ref=e723]: Alphascope provides informational tools only. Not financial advice. Trading prediction markets involves risk of loss.
  - alert [ref=e724]