- generic [active] [ref=e1]:
  - generic [ref=e2]:
    - banner [ref=e3]:
      - generic [ref=e4]:
        - img "cal" [ref=e6]
        - link [ref=e8] [cursor=pointer]:
          - /url: https://www.forebet.com/
        - generic [ref=e9]:
          - link [ref=e10] [cursor=pointer]:
            - /url: /en/favourite-predictions
          - generic [ref=e19] [cursor=pointer]: More
      - list [ref=e21]:
        - listitem [ref=e22]:
          - link [ref=e24] [cursor=pointer]:
            - /url: https://www.forebet.com/
            - img [ref=e25]
        - listitem [ref=e26]:
          - link "Football" [ref=e28] [cursor=pointer]:
            - /url: /en/football-tips-and-predictions-for-today
            - img [ref=e29]
            - text: Football
        - listitem [ref=e30]:
          - link "Basketball" [ref=e32] [cursor=pointer]:
            - /url: /en/basketball/predictions-today
            - img [ref=e33]
            - text: Basketball
        - listitem [ref=e34]:
          - link "Tennis" [ref=e36] [cursor=pointer]:
            - /url: /en/tennis/predictions-today
            - img [ref=e37]
            - text: Tennis
        - listitem [ref=e38]:
          - link "Hockey" [ref=e40] [cursor=pointer]:
            - /url: /en/hockey/predictions-today
            - img [ref=e41]
            - text: Hockey
        - listitem [ref=e42]:
          - link "Baseball" [ref=e43] [cursor=pointer]:
            - /url: /en/baseball/predictions-today
            - img [ref=e44]
            - text: Baseball
        - listitem [ref=e45]:
          - link "American Football" [ref=e46] [cursor=pointer]:
            - /url: /en/american-football/all-predictions
            - img [ref=e47]
            - text: American Football
        - listitem [ref=e48]:
          - link "MMA" [ref=e49] [cursor=pointer]:
            - /url: /en/mma/all-predictions
            - img [ref=e50]
            - text: MMA
        - listitem [ref=e51]:
          - link "Rugby" [ref=e52] [cursor=pointer]:
            - /url: /en/rugby/predictions-today
            - img [ref=e53]
            - text: Rugby
        - listitem [ref=e54]:
          - link "Volleyball" [ref=e55] [cursor=pointer]:
            - /url: /en/volleyball/predictions-today
            - img [ref=e56]
            - text: Volleyball
        - listitem [ref=e57]:
          - link "Handball" [ref=e58] [cursor=pointer]:
            - /url: /en/handball/predictions-today
            - img [ref=e59]
            - text: Handball
        - listitem [ref=e60]:
          - link "Cricket" [ref=e61] [cursor=pointer]:
            - /url: /en/cricket/predictions-today
            - img [ref=e62]
            - text: Cricket
        - listitem [ref=e63]:
          - link "AFL" [ref=e64] [cursor=pointer]:
            - /url: /en/afl/all-predictions
            - img [ref=e65]
            - text: AFL
        - listitem [ref=e66]:
          - link "Esoccer" [ref=e67] [cursor=pointer]:
            - /url: /en/esoccer/predictions-for-today
            - img [ref=e68]
            - text: Esoccer
    - generic [ref=e69]:
      - generic [ref=e70]:
        - generic [ref=e71]:
          - generic:
            - generic:
              - list
          - generic [ref=e72]:
            - generic [ref=e73]: My Leagues
            - list [ref=e75]:
              - listitem [ref=e76]:
                - generic [ref=e77]:
                  - link "United States" [ref=e78] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-usa
                  - generic [ref=e80] [cursor=pointer]: ">"
                - list [ref=e81]:
                  - listitem [ref=e82]:
                    - generic [ref=e83]:
                      - img [ref=e85] [cursor=pointer]
                      - generic [ref=e87]:
                        - link "MLS" [ref=e88] [cursor=pointer]:
                          - /url: /en/football-tips-and-predictions-for-usa/mls
                        - generic [ref=e89]: "6"
          - generic [ref=e90]:
            - generic [ref=e91]: Football
            - list [ref=e93]:
              - listitem [ref=e94]:
                - generic [ref=e95]:
                  - generic [ref=e96]:
                    - link "Predictions for TODAY" [ref=e97] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today
                    - generic [ref=e98]: "57"
                  - generic [ref=e100] [cursor=pointer]: ">"
                - list [ref=e101]:
                  - listitem [ref=e102]:
                    - link "Predictions 1X2" [ref=e105] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today/predictions-1x2
                  - listitem [ref=e106]:
                    - link "Under/Over 2.5 goals" [ref=e109] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today/predictions-under-over-goals
                  - listitem [ref=e110]:
                    - link "Half Time" [ref=e113] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today/predictions-ht
                  - listitem [ref=e114]:
                    - link "Half Time/Full Time" [ref=e117] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today/predictions-ht-ft
                  - listitem [ref=e118]:
                    - link "Both To Score" [ref=e121] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today/predictions-both-to-score
                  - listitem [ref=e122]:
                    - link "Double chance" [ref=e125] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today/double-chance-predictions
                  - listitem [ref=e126]:
                    - link "Asian handicap" [ref=e129] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today/asian-handicap
                  - listitem [ref=e130]:
                    - link "Goalscorers" [ref=e133] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today/predictions-goalscorers
                  - listitem [ref=e134]:
                    - link "Corners" [ref=e137] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today/corners
                  - listitem [ref=e138]:
                    - link "Cards" [ref=e141] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-today/cards
              - listitem [ref=e142]:
                - link "LIVE predictions" [ref=e145] [cursor=pointer]:
                  - /url: /en/live-football-tips
              - listitem [ref=e146]:
                - generic [ref=e147]:
                  - generic [ref=e148]:
                    - link "Predictions for TOMORROW" [ref=e149] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-tomorrow
                    - generic [ref=e150]: "39"
                  - generic [ref=e152] [cursor=pointer]: ">"
              - listitem [ref=e153]:
                - generic [ref=e154]:
                  - generic [ref=e155]:
                    - link "Predictions for the WEEKEND" [ref=e156] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-the-weekend
                    - generic [ref=e157]: "311"
                  - generic [ref=e159] [cursor=pointer]: ">"
              - listitem [ref=e160]:
                - generic [ref=e161]:
                  - link "Predictions from YESTERDAY" [ref=e163] [cursor=pointer]:
                    - /url: /en/football-predictions-from-yesterday
                  - generic [ref=e165] [cursor=pointer]: ">"
              - listitem [ref=e166]:
                - generic [ref=e167]:
                  - generic [ref=e168]:
                    - link "ALL predictions" [ref=e169] [cursor=pointer]:
                      - /url: /en/football-predictions
                    - generic [ref=e170]: "910"
                  - generic [ref=e172] [cursor=pointer]: ">"
              - listitem [ref=e173]:
                - link "TOP predictions" [ref=e176] [cursor=pointer]:
                  - /url: /en/top-football-tips-and-predictions
              - listitem [ref=e177]:
                - generic [ref=e179]:
                  - link "Values" [ref=e180] [cursor=pointer]:
                    - /url: /en/values
                  - generic [ref=e181]: "34"
              - listitem [ref=e182]:
                - link "Favourites" [ref=e185] [cursor=pointer]:
                  - /url: /en/favourite-predictions
              - listitem [ref=e186]:
                - generic [ref=e187]:
                  - link "Lists" [ref=e189] [cursor=pointer]:
                    - /url: /en/prediction-lists
                  - generic [ref=e191] [cursor=pointer]: ">"
        - generic [ref=e192]:
          - generic [ref=e193]:
            - generic [ref=e194]: Popular Leagues
            - list [ref=e196]:
              - listitem [ref=e197]:
                - generic [ref=e198]:
                  - img [ref=e199]
                  - link "UEFA Champions League" [ref=e201] [cursor=pointer]:
                    - /url: /en/predictions-europe/uefa-champions-league
              - listitem [ref=e202]:
                - generic [ref=e203]:
                  - img [ref=e204]
                  - link "UEFA Europa League" [ref=e206] [cursor=pointer]:
                    - /url: /en/predictions-europe/uefa-europa-league
              - listitem [ref=e207]:
                - generic [ref=e208]:
                  - img [ref=e209]
                  - link "UEFA Europa Conference League" [ref=e211] [cursor=pointer]:
                    - /url: /en/predictions-europe/uefa-europa-conference-league
              - listitem [ref=e212]:
                - generic [ref=e213]:
                  - img [ref=e214]
                  - link "Premier League" [ref=e216] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-england/premier-league
              - listitem [ref=e217]:
                - generic [ref=e218]:
                  - img [ref=e219]
                  - link "LaLiga" [ref=e221] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-spain/primera-division
              - listitem [ref=e222]:
                - generic [ref=e223]:
                  - img [ref=e224]
                  - link "Bundesliga" [ref=e226] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-germany/bundesliga
              - listitem [ref=e227]:
                - generic [ref=e228]:
                  - img [ref=e229]
                  - link "Serie A" [ref=e231] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-italy/serie-a
              - listitem [ref=e232]:
                - generic [ref=e233]:
                  - img [ref=e234]
                  - link "Ligue 1" [ref=e236] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-france/ligue1
              - listitem [ref=e237]:
                - generic [ref=e238]:
                  - img [ref=e239]
                  - link "Eredivisie" [ref=e241] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-netherlands/eredivisie
              - listitem [ref=e242]:
                - generic [ref=e243]:
                  - img [ref=e244]
                  - link "Liga Portugal" [ref=e246] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-portugal/liga-portugal
              - listitem [ref=e247]:
                - generic [ref=e248]:
                  - img [ref=e249]
                  - generic [ref=e250]:
                    - link "Brasileiro Serie A" [ref=e251] [cursor=pointer]:
                      - /url: /en/football-tips-and-predictions-for-brazil/serie-a
                    - generic [ref=e252]: "10"
              - listitem [ref=e253]:
                - generic [ref=e254]:
                  - img [ref=e255]
                  - link "Scottish Premiership" [ref=e257] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-scotland/premiership
              - listitem [ref=e258]:
                - generic [ref=e259]:
                  - img [ref=e260]
                  - link "Süper Lig" [ref=e262] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-turkey/super-lig
              - listitem [ref=e263]:
                - generic [ref=e264]:
                  - img [ref=e265]
                  - link "Saudi Pro League" [ref=e267] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-saudi-arabia/professional-league
          - generic [ref=e268]:
            - generic [ref=e269]: Countries
            - list [ref=e271]:
              - listitem [ref=e272]:
                - textbox "Search" [ref=e275]
              - listitem [ref=e276]:
                - generic [ref=e277]:
                  - link "Albania" [ref=e278] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-albania
                  - generic [ref=e280] [cursor=pointer]: ">"
              - listitem [ref=e281]:
                - generic [ref=e282]:
                  - link "Algeria" [ref=e283] [cursor=pointer]:
                    - /url: /en/tips-and-predictions-for-algeria
                  - generic [ref=e285] [cursor=pointer]: ">"
              - listitem [ref=e286]:
                - generic [ref=e287]:
                  - link "Andorra" [ref=e288] [cursor=pointer]:
                    - /url: /en/predictions-andorra
                  - generic [ref=e290] [cursor=pointer]: ">"
              - listitem [ref=e291]:
                - generic [ref=e292]:
                  - link "Angola" [ref=e293] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-angola
                  - generic [ref=e295] [cursor=pointer]: ">"
              - listitem [ref=e296]:
                - generic [ref=e297]:
                  - link "Antigua and Barbuda" [ref=e298] [cursor=pointer]:
                    - /url: /en/antigua-and-barbuda
                  - generic [ref=e300] [cursor=pointer]: ">"
              - listitem [ref=e301]:
                - generic [ref=e302]:
                  - link "Argentina" [ref=e303] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-argentina
                  - generic [ref=e305] [cursor=pointer]: ">"
              - listitem [ref=e306]:
                - generic [ref=e307]:
                  - link "Armenia" [ref=e308] [cursor=pointer]:
                    - /url: /en/tips-and-predictions-for-armenia
                  - generic [ref=e310] [cursor=pointer]: ">"
              - listitem [ref=e311]:
                - generic [ref=e312]:
                  - link "Aruba" [ref=e313] [cursor=pointer]:
                    - /url: /en/predictions-aruba
                  - generic [ref=e315] [cursor=pointer]: ">"
              - listitem [ref=e316]:
                - generic [ref=e317]:
                  - link "Australia" [ref=e318] [cursor=pointer]:
                    - /url: /en/tips-and-predictions-for-australia
                  - generic [ref=e320] [cursor=pointer]: ">"
              - listitem [ref=e321]:
                - generic [ref=e322]:
                  - link "Austria" [ref=e323] [cursor=pointer]:
                    - /url: /en/football-tips-and-predictions-for-austria
                  - generic [ref=e325] [cursor=pointer]: ">"
              - listitem [ref=e326]:
                - generic [ref=e327] [cursor=pointer]: More
          - generic [ref=e328]:
            - generic [ref=e329]: International
            - list [ref=e331]:
              - listitem [ref=e332]:
                - generic [ref=e333]:
                  - link "Africa" [ref=e334] [cursor=pointer]:
                    - /url: /en/predictions-africa
                  - generic [ref=e336] [cursor=pointer]: ">"
              - listitem [ref=e337]:
                - generic [ref=e338]:
                  - link "Asia" [ref=e339] [cursor=pointer]:
                    - /url: /en/predictions-asia
                  - generic [ref=e341] [cursor=pointer]: ">"
              - listitem [ref=e342]:
                - generic [ref=e343]:
                  - link "Australia & Oceania" [ref=e344] [cursor=pointer]:
                    - /url: /en/predictions-australia
                  - generic [ref=e346] [cursor=pointer]: ">"
              - listitem [ref=e347]:
                - generic [ref=e348]:
                  - link "Europe" [ref=e349] [cursor=pointer]:
                    - /url: /en/predictions-europe
                  - generic [ref=e351] [cursor=pointer]: ">"
              - listitem [ref=e352]:
                - generic [ref=e353]:
                  - link "North & Central America" [ref=e354] [cursor=pointer]:
                    - /url: /en/predictions-north-central-america
                  - generic [ref=e356] [cursor=pointer]: ">"
              - listitem [ref=e357]:
                - generic [ref=e358]:
                  - link "South America" [ref=e359] [cursor=pointer]:
                    - /url: /en/south-america
                  - generic [ref=e361] [cursor=pointer]: ">"
              - listitem [ref=e362]:
                - generic [ref=e363]:
                  - link "World" [ref=e364] [cursor=pointer]:
                    - /url: /en/predictions-world
                  - generic [ref=e366] [cursor=pointer]: ">"
      - generic [ref=e369]:
        - heading "Today (Finished matches) | 1X2 Predictions" [level=1] [ref=e370]
        - generic [ref=e371]:
          - list [ref=e374]:
            - listitem [ref=e375] [cursor=pointer]:
              - link "1X2" [ref=e376]:
                - /url: /en/football-tips-and-predictions-for-today/predictions-1x2
            - listitem [ref=e377] [cursor=pointer]:
              - link "Under/Over 2.5" [ref=e378]:
                - /url: /en/football-tips-and-predictions-for-today/predictions-under-over-goals
            - listitem [ref=e379] [cursor=pointer]:
              - link "1X2 Live" [ref=e380]:
                - /url: /en/live-football-tips
            - listitem [ref=e381] [cursor=pointer]:
              - link "Half Time" [ref=e382]:
                - /url: /en/football-tips-and-predictions-for-today/predictions-ht
            - listitem [ref=e383] [cursor=pointer]:
              - link "Half Time/Full Time" [ref=e384]:
                - /url: /en/football-tips-and-predictions-for-today/predictions-ht-ft
            - listitem [ref=e385] [cursor=pointer]:
              - link "Both To Score" [ref=e386]:
                - /url: /en/football-tips-and-predictions-for-today/predictions-both-to-score
            - listitem [ref=e387] [cursor=pointer]:
              - link "Double Chance" [ref=e388]:
                - /url: /en/football-tips-and-predictions-for-today/double-chance-predictions
            - listitem [ref=e389] [cursor=pointer]:
              - link "Handicap" [ref=e390]:
                - /url: /en/football-tips-and-predictions-for-today/asian-handicap
            - listitem [ref=e391] [cursor=pointer]:
              - link "Scorers" [ref=e392]:
                - /url: /en/football-tips-and-predictions-for-today/predictions-goalscorers
            - listitem [ref=e393] [cursor=pointer]:
              - link "Corners" [ref=e394]:
                - /url: /en/football-tips-and-predictions-for-today/corners
            - listitem [ref=e395] [cursor=pointer]:
              - link "Cards" [ref=e396]:
                - /url: /en/football-tips-and-predictions-for-today/cards
          - generic [ref=e398] [cursor=pointer]: ">"
        - list [ref=e402]:
          - listitem [ref=e403] [cursor=pointer]:
            - link "Upcoming" [ref=e404]:
              - /url: /en/football-tips-and-predictions-for-today
              - img [ref=e405]
              - text: Upcoming
          - listitem [ref=e406] [cursor=pointer]:
            - link "Finished" [ref=e407]:
              - /url: /en/football-tips-and-predictions-for-today/finished
              - img [ref=e408]
              - text: Finished
          - listitem [ref=e409] [cursor=pointer]:
            - link "League" [ref=e410]:
              - /url: /en/football-tips-and-predictions-for-today/by-league
              - img [ref=e411]
              - text: League
        - generic [ref=e412]:
          - generic [ref=e413]:
            - text: Home team
            - text: Away team
          - generic [ref=e414]:
            - generic [ref=e415]: Prob. %
            - generic [ref=e416]: "1"
            - generic [ref=e417]: X
            - generic [ref=e418]: "2"
          - generic [ref=e419]: Pred
          - generic [ref=e420]: Correct score
          - generic [ref=e421]: Avg. goals
          - generic [ref=e422]: Weather conditions
          - generic [ref=e423]: Coef.
          - generic [ref=e424]: Score
          - generic [ref=e425]:
            - text: Live
            - text: coef.
        - generic [ref=e426]: 01/06/2026
        - generic [ref=e427]:
          - generic [ref=e428]:
            - generic [ref=e430] [cursor=pointer]:
              - img [ref=e431]
              - text: Us4
            - link "Albion Colorado Flatirons Rush 06/01/2026 9:00 AM" [ref=e435] [cursor=pointer]:
              - /url: /en/football/matches/albion-colorado-flatirons-rush-2459623
              - generic [ref=e436]: Albion Colorado
              - generic [ref=e437]: Flatirons Rush
              - time [ref=e438]:
                - generic [ref=e439]: 06/01/2026 9:00 AM
            - generic [ref=e440]:
              - generic [ref=e441]: "35"
              - generic [ref=e442]: "31"
              - generic [ref=e443]: "34"
            - generic [ref=e445]: "1"
            - generic [ref=e446]: 1 - 0
            - generic [ref=e447]: "1.20"
            - generic [ref=e448]:
              - text: 63°F
              - img [ref=e449]
            - generic [ref=e451] [cursor=pointer]: "-"
            - generic [ref=e453]: FT
            - generic [ref=e454]:
              - generic [ref=e455] [cursor=pointer]: 3 - 2
              - generic [ref=e456]: (1 - 2)
          - generic [ref=e457]:
            - generic [ref=e459] [cursor=pointer]:
              - img [ref=e460]
              - text: Nz2
            - link "Northern AFC Coastal Spirit 06/01/2026 9:00 AM" [ref=e464] [cursor=pointer]:
              - /url: /en/football/matches/northern-afc-coastal-spirit-2441539
              - generic [ref=e465]: Northern AFC
              - generic [ref=e466]: Coastal Spirit
              - time [ref=e467]:
                - generic [ref=e468]: 06/01/2026 9:00 AM
            - generic [ref=e469]:
              - generic [ref=e470]: "37"
              - generic [ref=e471]: "25"
              - generic [ref=e472]: "38"
            - generic [ref=e474]: "2"
            - generic [ref=e475]: 0 - 2
            - generic [ref=e476]: "2.11"
            - generic [ref=e477]:
              - text: 61°F
              - img [ref=e478]
            - generic [ref=e480] [cursor=pointer]: "-152"
            - generic [ref=e482]: FT
            - generic [ref=e483]:
              - generic [ref=e484] [cursor=pointer]: 1 - 2
              - generic [ref=e485]: (1 - 1)
            - generic [ref=e487] [cursor=pointer]: "-"
          - generic [ref=e488]:
            - generic [ref=e490] [cursor=pointer]:
              - img [ref=e491]
              - text: Us4
            - link "Oly Town Ballard 06/01/2026 8:00 AM" [ref=e495] [cursor=pointer]:
              - /url: /en/football/matches/oly-town-ballard-2459622
              - generic [ref=e496]: Oly Town
              - generic [ref=e497]: Ballard
              - time [ref=e498]:
                - generic [ref=e499]: 06/01/2026 8:00 AM
            - generic [ref=e500]:
              - generic [ref=e501]: "22"
              - generic [ref=e502]: "14"
              - generic [ref=e503]: "64"
            - generic [ref=e505]: "2"
            - generic [ref=e506]: 0 - 3
            - generic [ref=e507]: "3.27"
            - generic [ref=e508]:
              - text: 70°F
              - img [ref=e509]
            - generic [ref=e511] [cursor=pointer]: "-"
            - generic [ref=e513]: FT
            - generic [ref=e514]:
              - generic [ref=e515] [cursor=pointer]: 1 - 2
              - generic [ref=e516]: (0 - 1)
          - generic [ref=e517]:
            - generic [ref=e519] [cursor=pointer]:
              - img [ref=e520]
              - text: Us4
            - link "RKC Rockford Raptors 06/01/2026 8:00 AM" [ref=e524] [cursor=pointer]:
              - /url: /en/football/matches/rkc-rockford-raptors-2459621
              - generic [ref=e525]: RKC
              - generic [ref=e526]: Rockford Raptors
              - time [ref=e527]:
                - generic [ref=e528]: 06/01/2026 8:00 AM
            - generic [ref=e529]:
              - generic [ref=e530]: "47"
              - generic [ref=e531]: "25"
              - generic [ref=e532]: "27"
            - generic [ref=e534]: "1"
            - generic [ref=e535]: 2 - 1
            - generic [ref=e536]: "3.00"
            - generic [ref=e537]:
              - text: 61°F
              - img [ref=e538]
            - generic [ref=e540] [cursor=pointer]: "-400"
            - generic [ref=e542]: FT
            - generic [ref=e543]:
              - generic [ref=e544] [cursor=pointer]: 0 - 2
              - generic [ref=e545]: (0 - 1)
            - generic [ref=e547] [cursor=pointer]: "-"
          - generic [ref=e549]:
            - generic [ref=e551] [cursor=pointer]:
              - img [ref=e552]
              - text: Cw1
            - link "Scherpenheuvel Inter Willemstad 06/01/2026 8:00 AM" [ref=e556] [cursor=pointer]:
              - /url: /en/football/matches/scherpenheuvel-inter-willemstad-2465183
              - generic [ref=e557]: Scherpenheuvel
              - generic [ref=e558]: Inter Willemstad
              - time [ref=e559]:
                - generic [ref=e560]: 06/01/2026 8:00 AM
            - generic [ref=e561]:
              - generic [ref=e562]: "38"
              - generic [ref=e563]: "32"
              - generic [ref=e564]: "30"
            - generic [ref=e566]: "1"
            - generic [ref=e567]: 2 - 1
            - generic [ref=e568]: "3.06"
            - generic [ref=e570] [cursor=pointer]: "-"
            - generic [ref=e572]: FT
            - generic [ref=e573]:
              - generic [ref=e574] [cursor=pointer]: 0 - 1
              - generic [ref=e575]: (0 - 1)
          - generic [ref=e576]:
            - generic [ref=e578] [cursor=pointer]:
              - img [ref=e579]
              - text: Aw1
            - link "Caravel Nacional 06/01/2026 8:00 AM" [ref=e583] [cursor=pointer]:
              - /url: /en/football/matches/caravel-nacional-2462877
              - generic [ref=e584]: Caravel
              - generic [ref=e585]: Nacional
              - time [ref=e586]:
                - generic [ref=e587]: 06/01/2026 8:00 AM
            - generic [ref=e588]:
              - generic [ref=e589]: "25"
              - generic [ref=e590]: "21"
              - generic [ref=e591]: "54"
            - generic [ref=e593]: "2"
            - generic [ref=e594]: 2 - 4
            - generic [ref=e595]: "4.33"
            - generic [ref=e596]:
              - text: 79°F
              - img [ref=e597]
            - generic [ref=e599] [cursor=pointer]: "-"
            - generic [ref=e601]: FT
            - generic [ref=e602]:
              - generic [ref=e603] [cursor=pointer]: 1 - 3
              - generic [ref=e604]: (1 - 0)
          - generic [ref=e605]:
            - generic [ref=e607] [cursor=pointer]:
              - img [ref=e608]
              - text: Uy2
            - link "Oriental (URU) Tacuarembó FC 06/01/2026 8:00 AM" [ref=e612] [cursor=pointer]:
              - /url: /en/football/matches/oriental-(uru)-tacuarembó-fc-2465146
              - generic [ref=e613]: Oriental (URU)
              - generic [ref=e614]: Tacuarembó FC
              - time [ref=e615]:
                - generic [ref=e616]: 06/01/2026 8:00 AM
            - generic [ref=e617]:
              - generic [ref=e618]: "26"
              - generic [ref=e619]: "39"
              - generic [ref=e620]: "35"
            - generic [ref=e622]: X
            - generic [ref=e623]: 1 - 1
            - generic [ref=e624]: "2.00"
            - generic [ref=e625]:
              - text: 55°F
              - img [ref=e626]
            - generic [ref=e628] [cursor=pointer]: "+190"
            - generic [ref=e630]: FT
            - generic [ref=e631]:
              - generic [ref=e632] [cursor=pointer]: 2 - 0
              - generic [ref=e633]: (1 - 0)
            - generic [ref=e635] [cursor=pointer]: "-"
          - generic [ref=e636]:
            - generic [ref=e638] [cursor=pointer]:
              - img [ref=e639]
              - text: Cl1
            - link "Palestino Audax Italiano 06/01/2026 8:00 AM" [ref=e643] [cursor=pointer]:
              - /url: /en/football/matches/palestino-audax-italiano-2419755
              - generic [ref=e644]: Palestino
              - generic [ref=e645]: Audax Italiano
              - time [ref=e646]:
                - generic [ref=e647]: 06/01/2026 8:00 AM
            - generic [ref=e648]:
              - generic [ref=e649]: "57"
              - generic [ref=e650]: "25"
              - generic [ref=e651]: "19"
            - generic [ref=e653]: "1"
            - generic [ref=e654]: 2 - 1
            - generic [ref=e655]: "3.36"
            - generic [ref=e656]:
              - text: 66°F
              - img [ref=e657]
            - generic [ref=e659] [cursor=pointer]: "-118"
            - generic [ref=e661]: FT
            - generic [ref=e662]:
              - generic [ref=e663] [cursor=pointer]: 0 - 0
              - generic [ref=e664]: (0 - 0)
            - generic [ref=e666] [cursor=pointer]: "-"
          - generic [ref=e667]:
            - generic [ref=e669] [cursor=pointer]:
              - img [ref=e670]
              - text: Us4
            - link "Virginia Marauders Hill City 06/01/2026 7:30 AM" [ref=e674] [cursor=pointer]:
              - /url: /en/football/matches/virginia-marauders-hill-city-2459597
              - generic [ref=e675]: Virginia Marauders
              - generic [ref=e676]: Hill City
              - time [ref=e677]:
                - generic [ref=e678]: 06/01/2026 7:30 AM
            - generic [ref=e679]:
              - generic [ref=e680]: "28"
              - generic [ref=e681]: "33"
              - generic [ref=e682]: "39"
            - generic [ref=e684]: "2"
            - generic [ref=e685]: 0 - 2
            - generic [ref=e686]: "0.00"
            - generic [ref=e687]:
              - text: 61°F
              - img [ref=e688]
            - generic [ref=e690] [cursor=pointer]: "-"
            - generic [ref=e692]: FT
            - generic [ref=e693]:
              - generic [ref=e694] [cursor=pointer]: 1 - 5
              - generic [ref=e695]: (0 - 3)
          - generic [ref=e696]:
            - generic [ref=e698] [cursor=pointer]:
              - img [ref=e699]
              - text: Br3
            - link "Figueirense Paysandu 06/01/2026 7:30 AM" [ref=e703] [cursor=pointer]:
              - /url: /en/football/matches/figueirense-paysandu-2448949
              - generic [ref=e704]: Figueirense
              - generic [ref=e705]: Paysandu
              - time [ref=e706]:
                - generic [ref=e707]: 06/01/2026 7:30 AM
            - generic [ref=e708]:
              - generic [ref=e709]: "21"
              - generic [ref=e710]: "13"
              - generic [ref=e711]: "66"
            - generic [ref=e713]: "2"
            - generic [ref=e714]: 1 - 2
            - generic [ref=e715]: "2.53"
            - generic [ref=e716]:
              - text: 72°F
              - img [ref=e717]
            - generic [ref=e719] [cursor=pointer]: "+240"
            - generic [ref=e721]: FT
            - generic [ref=e722]:
              - generic [ref=e723] [cursor=pointer]: 2 - 1
              - generic [ref=e724]: (1 - 1)
            - generic [ref=e726] [cursor=pointer]: "-"
          - generic [ref=e727]:
            - generic [ref=e729] [cursor=pointer]:
              - img [ref=e730]
              - text: Br2
            - link "Cuiabá CRB AL 06/01/2026 7:30 AM" [ref=e734] [cursor=pointer]:
              - /url: /en/football/matches/cuiabá-crb-al-2442765
              - generic [ref=e735]: Cuiabá
              - generic [ref=e736]: CRB AL
              - time [ref=e737]:
                - generic [ref=e738]: 06/01/2026 7:30 AM
            - generic [ref=e739]:
              - generic [ref=e740]: "23"
              - generic [ref=e741]: "36"
              - generic [ref=e742]: "41"
            - generic [ref=e744]: "2"
            - generic [ref=e745]: 0 - 2
            - generic [ref=e746]: "2.30"
            - generic [ref=e747]:
              - text: 86°F
              - img [ref=e748]
            - generic [ref=e750] [cursor=pointer]: "+250"
            - generic [ref=e752]: FT
            - generic [ref=e753]:
              - generic [ref=e754] [cursor=pointer]: 2 - 0
              - generic [ref=e755]: (2 - 0)
            - generic [ref=e757] [cursor=pointer]: "-"
          - generic [ref=e758]:
            - generic [ref=e760] [cursor=pointer]:
              - img [ref=e761]
              - text: Br1
            - link "Remo PA São Paulo 06/01/2026 7:30 AM" [ref=e765] [cursor=pointer]:
              - /url: /en/football/matches/remo-pa-são-paulo-2418067
              - generic [ref=e766]: Remo PA
              - generic [ref=e767]: São Paulo
              - time [ref=e768]:
                - generic [ref=e769]: 06/01/2026 7:30 AM
            - generic [ref=e770]:
              - generic [ref=e771]: "32"
              - generic [ref=e772]: "34"
              - generic [ref=e773]: "35"
            - generic [ref=e775]: "2"
            - generic [ref=e776]: 0 - 1
            - generic [ref=e777]: "1.63"
            - generic [ref=e778]:
              - text: 84°F
              - img [ref=e779]
            - generic [ref=e781] [cursor=pointer]: "+135"
            - generic [ref=e783]: FT
            - generic [ref=e784]:
              - generic [ref=e785] [cursor=pointer]: 1 - 0
              - generic [ref=e786]: (0 - 0)
            - generic [ref=e788] [cursor=pointer]: "-"
          - generic [ref=e789]:
            - generic [ref=e791] [cursor=pointer]:
              - img [ref=e792]
              - text: Br1
            - link "Cruzeiro Fluminense 06/01/2026 7:30 AM" [ref=e796] [cursor=pointer]:
              - /url: /en/football/matches/cruzeiro-fluminense-2418064
              - generic [ref=e797]: Cruzeiro
              - generic [ref=e798]: Fluminense
              - time [ref=e799]:
                - generic [ref=e800]: 06/01/2026 7:30 AM
            - generic [ref=e801]:
              - generic [ref=e802]: "32"
              - generic [ref=e803]: "31"
              - generic [ref=e804]: "36"
            - generic [ref=e806]: "2"
            - generic [ref=e807]: 1 - 2
            - generic [ref=e808]: "2.62"
            - generic [ref=e809]:
              - text: 75°F
              - img [ref=e810]
            - generic [ref=e812] [cursor=pointer]: "+333"
            - generic [ref=e814]: FT
            - generic [ref=e815]:
              - generic [ref=e816] [cursor=pointer]: 1 - 1
              - generic [ref=e817]: (0 - 1)
            - generic [ref=e819] [cursor=pointer]: "-"
          - generic [ref=e820]:
            - generic [ref=e822] [cursor=pointer]:
              - img [ref=e823]
              - text: Ec1
            - link "CS Emelec Univ Católica Quito 06/01/2026 7:15 AM" [ref=e827] [cursor=pointer]:
              - /url: /en/football/matches/cs-emelec-univ-católica-quito-2428035
              - generic [ref=e828]: CS Emelec
              - generic [ref=e829]: Univ Católica Quito
              - time [ref=e830]:
                - generic [ref=e831]: 06/01/2026 7:15 AM
            - generic [ref=e832]:
              - generic [ref=e833]: "38"
              - generic [ref=e834]: "30"
              - generic [ref=e835]: "32"
            - generic [ref=e837]: "1"
            - generic [ref=e838]: 2 - 1
            - generic [ref=e839]: "2.68"
            - generic [ref=e840]:
              - text: 90°F
              - img [ref=e841]
            - generic [ref=e843] [cursor=pointer]: "+162"
            - generic [ref=e845]: FT
            - generic [ref=e846]:
              - generic [ref=e847] [cursor=pointer]: 1 - 0
              - generic [ref=e848]: (0 - 0)
            - generic [ref=e850] [cursor=pointer]: "-"
          - generic [ref=e851]:
            - generic [ref=e853] [cursor=pointer]:
              - img [ref=e854]
              - text: Us4
            - link "Westchester Flames Staten Island Athletic 06/01/2026 7:00 AM" [ref=e858] [cursor=pointer]:
              - /url: /en/football/matches/westchester-flames-staten-island-athletic-2459620
              - generic [ref=e859]: Westchester Flames
              - generic [ref=e860]: Staten Island Athletic
              - time [ref=e861]:
                - generic [ref=e862]: 06/01/2026 7:00 AM
            - generic [ref=e863]:
              - generic [ref=e864]: "59"
              - generic [ref=e865]: "21"
              - generic [ref=e866]: "19"
            - generic [ref=e868]: "1"
            - generic [ref=e869]: 3 - 0
            - generic [ref=e870]: "2.83"
            - generic [ref=e871]:
              - text: 72°F
              - img [ref=e872]
            - generic [ref=e874] [cursor=pointer]: "+155"
            - generic [ref=e876]: FT
            - generic [ref=e877]:
              - generic [ref=e878] [cursor=pointer]: 1 - 3
              - generic [ref=e879]: (0 - 1)
            - generic [ref=e881] [cursor=pointer]: "-"
          - insertion [ref=e883]
  - generic [ref=e887]:
    - generic [ref=e888]:
      - link "Forebet Logo" [ref=e890] [cursor=pointer]:
        - /url: https://www.forebet.com/
        - img "Forebet Logo" [ref=e891]
      - generic [ref=e892]:
        - generic [ref=e893]:
          - generic [ref=e895]:
            - heading "GETTING STARTED" [level=6] [ref=e896]
            - list [ref=e897]:
              - listitem [ref=e898]:
                - link "What is Forebet?" [ref=e899] [cursor=pointer]:
                  - /url: /en/what-is-forebet
              - listitem [ref=e900]:
                - link "FAQ" [ref=e901] [cursor=pointer]:
                  - /url: /en/faq
              - listitem [ref=e902]:
                - link "Main features" [ref=e903] [cursor=pointer]:
                  - /url: /en/news-about-the-site/17463-main-features-of-forebet
              - listitem [ref=e904]:
                - link "Mobile App" [ref=e905] [cursor=pointer]:
                  - /url: /en/mobile-app
          - generic [ref=e907]:
            - heading "IMPORTANT" [level=6] [ref=e908]
            - list [ref=e909]:
              - listitem [ref=e910]:
                - link "Terms of use" [ref=e911] [cursor=pointer]:
                  - /url: /en/terms-of-use
              - listitem [ref=e912]:
                - link "Privacy policy" [ref=e913] [cursor=pointer]:
                  - /url: /en/privacy-policy
              - listitem [ref=e914]:
                - link "Avoid scam" [ref=e915] [cursor=pointer]:
                  - /url: /en/avoid-scam
              - listitem [ref=e916]:
                - link "Contact us" [ref=e917] [cursor=pointer]:
                  - /url: /en/contact-us
        - generic [ref=e918]:
          - generic [ref=e919]:
            - link "Facebook" [ref=e921] [cursor=pointer]:
              - /url: https://www.facebook.com/ForebetPredictions
              - img "Facebook" [ref=e922]
            - link [ref=e924] [cursor=pointer]:
              - /url: https://twitter.com/Forebet
              - img [ref=e925]
            - link [ref=e927] [cursor=pointer]:
              - /url: https://www.instagram.com/forebet.predictions/
              - img [ref=e928]
            - link [ref=e930] [cursor=pointer]:
              - /url: https://www.youtube.com/channel/UCvFtXcieLvPXTE8kaflW44Q
              - img [ref=e931]
            - link [ref=e933] [cursor=pointer]:
              - /url: https://www.tiktok.com/@forebet.predictions
              - img [ref=e934]
            - link [ref=e936] [cursor=pointer]:
              - /url: https://discord.gg/YN7YqaD78C
              - img [ref=e937]
            - link [ref=e939] [cursor=pointer]:
              - /url: https://www.threads.net/@forebet.predictions
              - img [ref=e940]
          - generic [ref=e941]:
            - link "Get the App on Google Play Button" [ref=e943] [cursor=pointer]:
              - /url: https://play.google.com/store/apps/details?id=com.devclev.forebet
              - img "Get the App on Google Play Button" [ref=e944]
            - link "Download the App on the App Store Button" [ref=e946] [cursor=pointer]:
              - /url: https://apps.apple.com/us/app/forebet-football-predictions/id6443482854
              - img "Download the App on the App Store Button" [ref=e947]
      - generic [ref=e948]:
        - generic [ref=e949]:
          - heading "ABOUT" [level=6] [ref=e950]
          - text: Football is mathematics. Forebet is a free data and analytics platform for football and sports predictions. It utilizes mathematical algorithms and statistical models to process historical match data across more than 850 football leagues and other major sports competitions worldwide. Since 2009, Forebet has leveraged the power of mathematical algorithms and statistical models to transform raw data into actionable intelligence, match analytics, and data-driven sports predictions for fans worldwide. The platform is designed to support informed decision-making by presenting objective probabilities and structured football and sports statistics.
        - generic [ref=e951]:
          - generic [ref=e952]:
            - heading "PREDICTIONS" [level=6] [ref=e953]
            - list [ref=e954]:
              - listitem [ref=e955]:
                - link "Football Predictions For Today" [ref=e956] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/football-tips-and-predictions-for-today
              - listitem [ref=e957]:
                - link "Football Predictions For Tomorrow" [ref=e958] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/football-tips-and-predictions-for-tomorrow
              - listitem [ref=e959]:
                - link "Football Predictions the Weekend" [ref=e960] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/football-tips-and-predictions-for-the-weekend
              - listitem [ref=e961]:
                - link "Premier League" [ref=e962] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/football-tips-and-predictions-for-england/premier-league
              - listitem [ref=e963]:
                - link "La Liga" [ref=e964] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/football-tips-and-predictions-for-spain/primera-division
              - listitem [ref=e965]:
                - link "Bundesliga" [ref=e966] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/football-tips-and-predictions-for-germany/Bundesliga
              - listitem [ref=e967]:
                - link "Serie A" [ref=e968] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/football-tips-and-predictions-for-italy/serie-a
              - listitem [ref=e969]:
                - link "Ligue 1" [ref=e970] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/football-tips-and-predictions-for-france/ligue1
              - listitem [ref=e971]:
                - link "Eredivisie" [ref=e972] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/football-tips-and-predictions-for-netherlands/eredivisie
              - listitem [ref=e973]:
                - link "Champions League" [ref=e974] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/predictions-europe/uefa-champions-league
              - listitem [ref=e975]:
                - link "Europa League" [ref=e976] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/predictions-europe/uefa-europa-league
              - listitem [ref=e977]:
                - link "Conference League" [ref=e978] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/predictions-europe/uefa-europa-conference-league
          - generic [ref=e979]:
            - heading "MORE" [level=6] [ref=e980]
            - list [ref=e981]:
              - listitem [ref=e982]:
                - link "Match previews" [ref=e983] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/football-match-previews
              - listitem [ref=e984]:
                - link "Live-score" [ref=e985] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/livescore
              - listitem [ref=e986]:
                - link "Trends" [ref=e987] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/trends
              - listitem [ref=e988]:
                - link "Basketball" [ref=e989] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/basketball/predictions-today
              - listitem [ref=e990]:
                - link "Tennis" [ref=e991] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/tennis/predictions-today
              - listitem [ref=e992]:
                - link "Hockey" [ref=e993] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/hockey/predictions-today
              - listitem [ref=e994]:
                - link "Baseball" [ref=e995] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/baseball/predictions-today
              - listitem [ref=e996]:
                - link "American Football" [ref=e997] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/american-football/all-predictions
              - listitem [ref=e998]:
                - link "MMA" [ref=e999] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/mma/all-predictions
              - listitem [ref=e1000]:
                - link "Rugby" [ref=e1001] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/rugby/predictions-today
              - listitem [ref=e1002]:
                - link "Handball" [ref=e1003] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/handball/predictions-today
              - listitem [ref=e1004]:
                - link "Volleyball" [ref=e1005] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/volleyball/predictions-today
              - listitem [ref=e1006]:
                - link "Cricket" [ref=e1007] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/cricket/predictions-today
              - listitem [ref=e1008]:
                - link "Esoccer" [ref=e1009] [cursor=pointer]:
                  - /url: https://www.forebet.com/en/esoccer
    - generic [ref=e1011]: Copyright © 2009-2025 Forebet.com All rights reserved.